spring.application.name=RestWeb_PersonEample
server.port= 8085
spring.datasource.url= jdbc:mysql://localhost:3306/sample
spring.datasource.driverClassName= com.mysql.cj.jdbc.Driver
spring.datasource.username= root
spring.datasource.password= vijay@123

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.data.jpa.repositories.enabled=true
#spring.jpa.hibernate.ddl-auto=update

